package io.github.scala_tessella.research_core.render

/** A minimal page-description IR with TWO backends, PDF and encapsulated PostScript, so a figure is described
  * once and emitted in both formats from the same description.
  *
  * WHY THIS EXISTS. Some journals do not accept PDF artwork at all, wanting EPS or PostScript instead. The
  * obvious route — build the figures with LaTeX and convert with Ghostscript — needs a toolchain this
  * programme does not otherwise require, and it repairs downstream what can simply be produced correctly
  * upstream: these figures are generated by our own code, so the output format is a generation parameter,
  * exactly as stroke width turned out to be. Emitting EPS directly also removes the LaTeX composite build
  * entirely.
  *
  * THE GENERAL CASE the other emitters here are special cases of: [[PdfFigure]] is this with one stroke
  * width, filled polygons and no text; a honeycomb page is this with labels. Neither is expressed through it,
  * because both have byte-frozen output and this backend emits a `/Font` resource — but new emitters should
  * start here.
  *
  * COORDINATES are POINTS on the final page, origin bottom-left, y up — what PDF and PostScript both use
  * natively, so neither backend needs a transform matrix. A stroke width in this IR is therefore the PRINTED
  * width, with nothing left to scale it: see [[FigurePolicy.StrokePt]].
  *
  * FONTS are the two standard ones this artwork needs, Helvetica and Symbol. Both sit on the short list of
  * faces journals permit (Arial, Courier, Helvetica, Symbol, Times) and both are base fonts of PDF and of
  * every PostScript interpreter, so nothing is embedded and nothing can be substituted for something else.
  *
  * IO-free, like everything in `core`: both backends return the document as a string. Writing the pair side
  * by side is the caller's business (`uniform_tilings.FigureIO.write`).
  */
object FigureCanvas:

  /** For [[Shape.Label]], `x` is the horizontal CENTRE of the text and `y` its baseline: both backends offset
    * by half the measured width when they emit it.
    */
  enum Shape:
    case Poly(pts: Vector[Pt], fill: (Double, Double, Double))
    case Seg(a: Pt, b: Pt)
    case Label(x: Double, y: Double, text: String, symbol: Boolean, size: Double)

    /** A closed path whose sides are S-CURVES: each edge becomes a cubic whose two control points are offset
      * perpendicular to it by `+h` then `-h`, `h = bulge · |edge|`, so the curve is ODD about the edge
      * midpoint.
      *
      * That oddness is the whole construction, not a stylistic choice. A shared edge is traversed in opposite
      * directions by its two faces; under reversal the two control points swap AND the left normal flips, so
      * both faces produce the identical curve — the perturbation is well defined on the tiling. It is carried
      * by every rotation (orientation preserved, so left stays left) and reversed by every reflection (each S
      * becomes its mirror image, a different curve). The tiling therefore keeps all its rotations and loses
      * all its mirrors: it becomes chiral.
      *
      * That is precisely the freedom the topological category has and straight unit edges do not, which is
      * why 62 of the 93 types are realizable only with excess symmetry.
      */
    case Curved(
        pts: Vector[Pt],
        bulge: Double,
        fill: Option[(Double, Double, Double)],
        strokePt: Double,
        ink: (Double, Double, Double)
    )

  import Shape.*

  /** The cubic control points of the S-curve on each side of a closed path: `(c1, c2, end)` per side. */
  private def sCurves(pts: Vector[Pt], bulge: Double): Vector[(Pt, Pt, Pt)] =
    pts.indices.toVector.map { i =>
      val (a, b)   = (pts(i), pts((i + 1) % pts.size))
      val (dx, dy) = (b.x - a.x, b.y - a.y)
      val h        = bulge // as a fraction of the edge, so the offset scales with it
      // left normal of a->b, times |edge| times bulge
      val (nx, ny) = (-dy * h, dx * h)
      ((a.x + dx / 3 + nx, a.y + dy / 3 + ny), (a.x + 2 * dx / 3 - nx, a.y + 2 * dy / 3 - ny), b)
    }

  final case class Figure(width: Double, height: Double, strokePt: Double, shapes: Vector[Shape])

  private def num(v: Double): String = String.format(java.util.Locale.ROOT, "%.2f", v)

  /** Character widths in 1/1000 em, from the Adobe AFMs, for the only glyphs this artwork uses. They are
    * needed because centring text requires knowing its width, and PDF — unlike PostScript, which has
    * `stringwidth` — offers no way to ask at render time. Unlisted characters fall back to 556, Helvetica's
    * commonest width; add to the table rather than relying on that if a new label appears.
    */
  private val helvetica = Map(
    '(' -> 333,
    ')' -> 333,
    'a' -> 556,
    'b' -> 556,
    'c' -> 500,
    'd' -> 556,
    '-' -> 333,
    'o' -> 556,
    'r' -> 333,
    's' -> 500,
    'w' -> 722,
    ' ' -> 278
  )

  /** Symbol's lower-case Greek sits at the Latin code points: 'a' prints alpha, 'b' beta. */
  private val symbolFont = Map('a' -> 631, 'b' -> 549)

  def textWidth(text: String, symbol: Boolean, size: Double): Double =
    val table = if symbol then symbolFont else helvetica
    text.map(c => table.getOrElse(c, 556)).sum * size / 1000.0

  // Helvetica's ascent and descent, used to give a Label a bounding box
  private inline val Ascent  = 0.72
  private inline val Descent = 0.21

  private def bounds(s: Shape): (Double, Double, Double, Double) = s match
    case Poly(pts, _)                =>
      (pts.map(_.x).min, pts.map(_.y).min, pts.map(_.x).max, pts.map(_.y).max)
    case Seg(a, b)                   =>
      (math.min(a.x, b.x), math.min(a.y, b.y), math.max(a.x, b.x), math.max(a.y, b.y))
    case Label(x, y, t, sym, size)   =>
      val half = textWidth(t, sym, size) / 2
      (x - half, y - Descent * size, x + half, y + Ascent * size)
    case Curved(pts, bulge, _, _, _) =>
      // a cubic stays inside the convex hull of its control polygon, so the control points bound it
      val all = pts ++ sCurves(pts, bulge).flatMap((c1, c2, _) => Vector(c1, c2))
      (all.map(_.x).min, all.map(_.y).min, all.map(_.x).max, all.map(_.y).max)

  private def shift(s: Shape, dx: Double, dy: Double): Shape = s match
    case Poly(pts, fill)              => Poly(pts.map(p => (p.x + dx, p.y + dy)), fill)
    case Seg(a, b)                    => Seg((a.x + dx, a.y + dy), (b.x + dx, b.y + dy))
    case Label(x, y, t, sym, size)    => Label(x + dx, y + dy, t, sym, size)
    case Curved(pts, b, fill, w, ink) => Curved(pts.map(p => (p.x + dx, p.y + dy)), b, fill, w, ink)

  /** Wrap shapes in a page cropped to their extent plus `margin` on every side — the "remove extraneous white
    * space, do not draw a box" rule journal artwork guides state, applied at emission.
    */
  def fitted(shapes: Vector[Shape], margin: Double, strokePt: Double): Figure =
    val bs       = shapes.map(bounds)
    val (x0, y0) = (bs.map(_._1).min - margin, bs.map(_._2).min - margin)
    val (x1, y1) = (bs.map(_._3).max + margin, bs.map(_._4).max + margin)
    Figure(x1 - x0, y1 - y0, strokePt, shapes.map(shift(_, -x0, -y0)))

  private def escape(s: String): String = s.flatMap:
    case c @ ('(' | ')' | '\\') => s"\\$c"
    case c                      => c.toString

  private def path(pts: Vector[Pt], op: String): String =
    pts.zipWithIndex
      .map((p, i) => s"${num(p.x)} ${num(p.y)} ${if i == 0 then "m" else "l"}")
      .mkString(" ") + s" $op\n"

  /** The shared hand-written PDF 1.4 ([[PdfDocument]]), plus a text object and the two standard fonts. */
  def toPdf(fig: Figure): String =
    val content = StringBuilder()
    content ++= s"${num(fig.strokePt)} w 0.13 0.13 0.13 RG 1 j 1 J\n"
    for s <- fig.shapes do
      s match
        case Poly(pts, (r, g, b))                      =>
          content ++= s"${num(r)} ${num(g)} ${num(b)} rg\n"
          content ++= path(pts, "h B")
        case Seg(a, b)                                 =>
          content ++= s"${num(a.x)} ${num(a.y)} m ${num(b.x)} ${num(b.y)} l S\n"
        case Label(x, y, t, sym, size)                 =>
          val left = x - textWidth(t, sym, size) / 2
          content ++=
            s"0 0 0 rg BT /${if sym then "F2" else "F1"} ${num(size)} Tf " +
              s"${num(left)} ${num(y)} Td (${escape(t)}) Tj ET\n"
        case Curved(pts, bulge, fill, w, (ir, ig, ib)) =>
          content ++= s"q ${num(w)} w ${num(ir)} ${num(ig)} ${num(ib)} RG\n"
          fill.foreach((r, g, b) => content ++= s"${num(r)} ${num(g)} ${num(b)} rg\n")
          content ++= s"${num(pts.head.x)} ${num(pts.head.y)} m\n"
          for (c1, c2, e) <- sCurves(pts, bulge) do
            content ++= s"${num(c1.x)} ${num(c1.y)} ${num(c2.x)} ${num(c2.y)} ${num(e.x)} ${num(e.y)} c\n"
          content ++= (if fill.isDefined then "h B\nQ\n" else "h S\nQ\n")
    val stream  = content.toString
    val fonts   =
      "/Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> " +
        "/F2 << /Type /Font /Subtype /Type1 /BaseFont /Symbol >> >>"
    PdfDocument(
      PdfDocument.preamble ++
        Vector(
          PdfDocument.page(fig.width, fig.height, s"<< $fonts >>"),
          PdfDocument.contents(stream)
        )
    )

  /** Encapsulated PostScript — THE FORMAT UPLOADED AS ARTWORK.
    *
    * `%%BoundingBox` must be integers and is rounded outwards; `%%HiResBoundingBox` carries the exact box for
    * anything that reads it. `showpage` is included: strict EPSF discourages it, but every embedder redefines
    * it, Ghostscript's own `eps2write` emits it, and without it some viewers show a blank page.
    */
  def toEps(fig: Figure): String =
    val sb = StringBuilder()
    sb ++= "%!PS-Adobe-3.0 EPSF-3.0\n"
    sb ++= s"%%BoundingBox: 0 0 ${math.ceil(fig.width).toInt} ${math.ceil(fig.height).toInt}\n"
    sb ++= s"%%HiResBoundingBox: 0 0 ${num(fig.width)} ${num(fig.height)}\n"
    sb ++= "%%Creator: scala-tessella uniform-tilings (FigureCanvas)\n"
    sb ++= "%%LanguageLevel: 2\n%%Pages: 1\n%%EndComments\n"
    sb ++= s"${num(fig.strokePt)} setlinewidth 1 setlinejoin 1 setlinecap\n"
    sb ++= "0.13 0.13 0.13 setrgbcolor\n"
    for s <- fig.shapes do
      s match
        case Poly(pts, (r, g, b))                      =>
          sb ++= "newpath " +
            pts.zipWithIndex
              .map((p, i) => s"${num(p.x)} ${num(p.y)} ${if i == 0 then "moveto" else "lineto"}")
              .mkString(" ")
          // gsave/grestore around the fill so the dark stroke colour survives it
          sb ++= s" closepath\ngsave ${num(r)} ${num(g)} ${num(b)} setrgbcolor fill grestore stroke\n"
        case Seg(a, b)                                 =>
          sb ++= s"newpath ${num(a.x)} ${num(a.y)} moveto ${num(b.x)} ${num(b.y)} lineto stroke\n"
        case Label(x, y, t, sym, size)                 =>
          val left = x - textWidth(t, sym, size) / 2
          sb ++= s"/${if sym then "Symbol" else "Helvetica"} findfont ${num(size)} scalefont setfont\n"
          sb ++= s"0 0 0 setrgbcolor ${num(left)} ${num(y)} moveto (${escape(t)}) show\n"
          sb ++= "0.13 0.13 0.13 setrgbcolor\n"
        case Curved(pts, bulge, fill, w, (ir, ig, ib)) =>
          sb ++= s"gsave ${num(w)} setlinewidth ${num(ir)} ${num(ig)} ${num(ib)} setrgbcolor\n"
          sb ++= s"newpath ${num(pts.head.x)} ${num(pts.head.y)} moveto\n"
          for (c1, c2, e) <- sCurves(pts, bulge) do
            sb ++=
              s"${num(c1.x)} ${num(c1.y)} ${num(c2.x)} ${num(c2.y)} ${num(e.x)} ${num(e.y)} curveto\n"
          sb ++= "closepath\n"
          fill match
            case Some((r, g, b)) => sb ++=
                s"gsave ${num(r)} ${num(g)} ${num(b)} setrgbcolor fill grestore stroke\n"
            case None            => sb ++= "stroke\n"
          sb ++= "grestore\n"
    sb ++= "showpage\n%%EOF\n"
    sb.toString
