package io.github.scala_tessella.research_core

import MonoShell.{geomOf, gluings, Flags, Glu, Rot, StarGeom, Vec}
import SpeciesEnumerator.species

/** Transitive gluing patterns and rigid development — the enumeration engine over the vertex species.
  *
  * THEORY. A vertex-transitive honeycomb H with species S yields, for every tiling-vertex x of the placed
  * star, a symmetry γₓ ∈ Sym(H) with γₓ(v₀) = uₓ; the tuple (γₓ) is a PATTERN: one atlas gluing per
  * tiling-vertex satisfying (R1) γₓ·γ_y(x) ∈ Stab(S) (the placed star's symmetry group) for the back-vertex
  * y(x), and (R2) for every face F of the star, the word obtained by walking around F — at each step the next
  * generator is read off in base coordinates by transporting the face germ through the gluing — lands in
  * Stab(S). Conversely a pattern satisfying (R1)+(R2) DEVELOPS: the stars at words w are w(S), the relations
  * of the honeycomb's simply-connected (edge, face) 2-complex are generated by reverse edges and face cycles,
  * so the development is well-defined, every point has a full neighborhood (stars are balls, rings are
  * closed), and the developing map is a covering of E³ — hence a genuine honeycomb, transitive by
  * construction since each γₓ maps stars to stars. Enumerating patterns therefore captures EVERY transitive
  * honeycomb (completeness) and produces ONLY transitive honeycombs (soundness).
  *
  * FORCING THEOREM (single-coset species). The neighbor star placed by a gluing g is g(S), which depends only
  * on the coset g·Stab(S). If at every tiling-vertex ALL atlas gluings lie in one coset, then in any
  * mono-species honeycomb the star of every neighbor is forced by the star at the vertex, and by induction
  * along paths the entire honeycomb is determined by star(v₀): AT MOST ONE mono-species honeycomb exists, and
  * one consistent pattern proves existence — no enumeration needed, and the count is rigorous.
  *
  * MULTI-COSET SPECIES. Enumerate coset SKELETONS (a placement choice per vertex — these are the germs that
  * distinguish e.g. the elongated from the gyroelongated alternated cubic), then search consistent patterns
  * within each skeleton and dedup by canonical development fingerprints (the ball of radius R of the
  * developed honeycomb, canonicalized over Stab(S)), computed at two radii as a stability check. Every
  * transitive honeycomb appears in its own skeleton, so coverage is complete; the identification of equal
  * honeycombs across patterns is fingerprint-based at finite radius; that finite radius and the per-skeleton
  * pattern sampling cap are what [[CompletenessAudit]] discharges.
  */
object TransitivePatterns:

  // ---------- small linear algebra (doubles on interval midpoints, as in MonoShell) ----------

  private def vSub(a: Vec, b: Vec): Vec      = (a._1 - b._1, a._2 - b._2, a._3 - b._3)
  private def vAdd(a: Vec, b: Vec): Vec      = (a._1 + b._1, a._2 + b._2, a._3 + b._3)
  private def vDot(a: Vec, b: Vec): Double   = a._1 * b._1 + a._2 * b._2 + a._3 * b._3
  private def vScale(a: Vec, s: Double): Vec = (a._1 * s, a._2 * s, a._3 * s)
  private def vNorm(a: Vec): Double          = math.sqrt(vDot(a, a))
  private def vUnit(a: Vec): Vec             = vScale(a, 1.0 / vNorm(a))
  private def vDist(a: Vec, b: Vec): Double  = vNorm(vSub(a, b))

  /** 3×3 matrix by rows. */
  final case class Mat(r1: Vec, r2: Vec, r3: Vec):
    def apply(v: Vec): Vec   = (vDot(r1, v), vDot(r2, v), vDot(r3, v))
    def t: Mat               =
      Mat((r1._1, r2._1, r3._1), (r1._2, r2._2, r3._2), (r1._3, r2._3, r3._3))
    def *(o: Mat): Mat       =
      val ot = o.t
      Mat(
        (vDot(r1, ot.r1), vDot(r1, ot.r2), vDot(r1, ot.r3)),
        (vDot(r2, ot.r1), vDot(r2, ot.r2), vDot(r2, ot.r3)),
        (vDot(r3, ot.r1), vDot(r3, ot.r2), vDot(r3, ot.r3))
      )
    def dist(o: Mat): Double =
      vDist(r1, o.r1) + vDist(r2, o.r2) + vDist(r3, o.r3)

  private[research_core] val idMat = Mat((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0))

  def matOf(rot: Rot): Mat =
    val c1 = rot((1.0, 0.0, 0.0))
    val c2 = rot((0.0, 1.0, 0.0))
    val c3 = rot((0.0, 0.0, 1.0))
    Mat((c1._1, c2._1, c3._1), (c1._2, c2._2, c3._2), (c1._3, c2._3, c3._3))

  /** Rigid motion p ↦ m(p) + t. */
  final case class Iso(m: Mat, t: Vec):
    def apply(p: Vec): Vec   = vAdd(m(p), t)
    def compose(o: Iso): Iso = Iso(m * o.m, apply(o.t)) // this ∘ o

  private val matchTol = 1e-6

  // ---------- the star's symmetry group and the coset structure ----------

  /** Base corner data of a species: per corner, (cell ordinal, unit vertex directions). */
  private[research_core] def cornerData(g: StarGeom): Vector[(Int, Vector[Vec])] =
    g.st.corners.map { pl =>
      (pl.cell.ordinal, pl.verts.map(v => vUnit((v._1.mid, v._2.mid, v._3.mid))))
    }

  private[research_core] def round4(v: Vec): (Long, Long, Long) =
    (math.round(v._1 * 1e4), math.round(v._2 * 1e4), math.round(v._3 * 1e4))

  /** Canonical signature of the star transformed by m: the sorted corner encoding. */
  private[research_core] def starSig(
      corners: Vector[(Int, Vector[Vec])],
      m: Mat
  ): Vector[(Int, Vector[(Long, Long, Long)])] =
    import scala.math.Ordering.Implicits.seqOrdering
    corners.map((c, ds) => (c, ds.map(d => round4(m(d))).sorted)).sorted

  /** Stab(S): all orthogonal maps fixing the placed star (candidates from frame alignments over the gluing
    * atlas machinery would do; here directly: map u₀ to any u_z with any arc frame and ±det, keep those
    * preserving the corner signature).
    */
  def stabilizers(g: StarGeom, corners: Vector[(Int, Vector[Vec])]): Vector[Mat] =
    val sig0                         = starSig(corners, idMat)
    def inPlane(v: Int, w: Int): Vec = vUnit(vSub(g.u(w), vScale(g.u(v), vDot(g.u(w), g.u(v)))))
    def arcsAt(v: Int): Vector[Int]  =
      g.st.arcs.keys.toVector.collect {
        case (a, b) if a == v => b
        case (a, b) if b == v => a
      }
    val found                        = collection.mutable.ArrayBuffer.empty[Mat]
    val w0                           = arcsAt(0).head
    val a1                           = g.u(0)
    val a2                           = inPlane(0, w0)
    val a3                           =
      ((a1._2 * a2._3 - a1._3 * a2._2), (a1._3 * a2._1 - a1._1 * a2._3), (a1._1 * a2._2 - a1._2 * a2._1))
    for
      z   <- g.u.indices
      w   <- arcsAt(z)
      det <- Vector(1.0, -1.0)
    do
      val b1  = g.u(z)
      val b2  = inPlane(z, w)
      val b3  = vScale(
        ((b1._2 * b2._3 - b1._3 * b2._2), (b1._3 * b2._1 - b1._1 * b2._3), (b1._1 * b2._2 - b1._2 * b2._1)),
        det
      )
      // R maps frame a → frame b
      val rot = Mat(
        (
          b1._1 * a1._1 + b2._1 * a2._1 + b3._1 * a3._1,
          b1._1 * a1._2 + b2._1 * a2._2 + b3._1 * a3._2,
          b1._1 * a1._3 + b2._1 * a2._3 + b3._1 * a3._3
        ),
        (
          b1._2 * a1._1 + b2._2 * a2._1 + b3._2 * a3._1,
          b1._2 * a1._2 + b2._2 * a2._2 + b3._2 * a3._2,
          b1._2 * a1._3 + b2._2 * a2._3 + b3._2 * a3._3
        ),
        (
          b1._3 * a1._1 + b2._3 * a2._1 + b3._3 * a3._1,
          b1._3 * a1._2 + b2._3 * a2._2 + b3._3 * a3._2,
          b1._3 * a1._3 + b2._3 * a2._3 + b3._3 * a3._3
        )
      )
      if starSig(corners, rot) == sig0 && !found.exists(_.dist(rot) < 1e-6) then found += rot
    found.toVector

  // ---------- patterns ----------

  final case class Pattern(g: StarGeom, glus: Vector[Glu]):
    def iso(x: Int): Iso = Iso(matOf(glus(x).rot), g.u(x))

  private[research_core] def inStab(m: Mat, stab: Vector[Mat]): Boolean = stab.exists(_.dist(m) < 1e-5)

  /** Walk the face of arc `key` under a partial assignment. Returns Left(vertex needed), or Right(Some(word))
    * when closed, or Right(None) when the walk is geometrically inconsistent.
    */
  private def walkFace(
      g: StarGeom,
      assigned: Int => Option[Glu],
      key: (Int, Int)
  ): Either[Int, Option[Iso]] =
    val p                            = g.st.arcs(key).face
    def inPlane(v: Int, w: Int): Vec = vUnit(vSub(g.u(w), vScale(g.u(v), vDot(g.u(w), g.u(v)))))
    def arcsAt(v: Int): Vector[Int]  =
      g.st.arcs.keys.toVector.collect {
        case (a, b) if a == v => b
        case (a, b) if b == v => a
      }
    var exit                         = key._1
    var interior                     = inPlane(key._1, key._2) // interior dir of F at edge (0, u_exit)
    var word                         = Iso(idMat, (0.0, 0.0, 0.0))
    var steps                        = 0
    while steps < p do
      assigned(exit) match
        case None      => return Left(exit)
        case Some(glu) =>
          val m  = matOf(glu.rot)
          word = word.compose(Iso(m, g.u(exit)))
          val mt = m.t
          val dI = mt(interior) // the face's interior dir at the shared edge, in the new base
          val y  = glu.y
          val z  = arcsAt(y).find(z => vDist(inPlane(y, z), dI) < 1e-4)
          z match
            case None     => return Right(None) // no face continuation: geometric inconsistency
            case Some(zz) =>
              exit = zz
              interior = inPlane(zz, y)
      steps += 1
    Right(Some(word))

  /** DFS over pattern assignments within the given per-vertex domains; every consistent pattern is passed to
    * `emit`. Returns (patterns found, whether the search was capped).
    */
  private[research_core] def searchPatterns(
      g: StarGeom,
      domains: Vector[Vector[Glu]],
      stab: Vector[Mat],
      cap: Int,
      emit: Vector[Glu] => Unit
  ): (Int, Boolean) =
    val n                               = domains.size
    val chosen                          = Array.fill[Option[Glu]](n)(None)
    val arcKeys                         = g.st.arcs.keys.toVector.sorted
    var found                           = 0
    var capped                          = false
    def consistent(): Option[Int]       = // Some(vertex needed) or None when all checks pass so far
      var need: Option[Int] = None
      val ok                = arcKeys.forall { key =>
        walkFace(g, x => chosen(x), key) match
          case Left(v)        => if need.isEmpty then need = Some(v); true
          case Right(Some(w)) => vNorm(w.t) < 1e-5 && inStab(w.m, stab)
          case Right(None)    => false
      }
      if !ok then Some(-1) else need
    def r1ok(x: Int, glu: Glu): Boolean =
      // (i) x's own reverse pair, when its partner is already assigned
      val fwd = chosen(glu.y) match
        case Some(gy) => inStab(matOf(glu.rot) * matOf(gy.rot), stab)
        case None     => true
      // (ii) reverse pairs of earlier vertices whose back-vertex is x
      fwd && chosen.indices.forall { x2 =>
        x2 == x ||
        (chosen(x2) match
          case Some(g2) if g2.y == x => inStab(matOf(g2.rot) * matOf(glu.rot), stab)
          case _                     => true)
      }
    def bt(): Unit                      =
      if found >= cap then { capped = true; return }
      // while, not for-do: a `return` inside the desugared foreach closure would be non-local
      consistent() match
        case Some(-1) => () // dead branch
        case Some(v)  =>
          val glus = domains(v)
          var i    = 0
          while i < glus.length && found < cap do
            val glu = glus(i)
            if r1ok(v, glu) then
              chosen(v) = Some(glu)
              bt()
              chosen(v) = None
            i += 1
          // candidates remained when the cap broke the loop: the search WAS truncated. This check was
          // historically missing from this branch — and cap-hit unwinds pass (in practice: only) through
          // Some(v) frames, so truncation went entirely unreported (measured: 43/43 truncated corpus
          // searches reported uncapped). The exhaustion certificate consumes this flag; see CappedProbeSpec.
          if i < glus.length then capped = true
        case None     =>
          chosen.indexWhere(_.isEmpty) match
            case -1 =>
              found += 1
              emit(chosen.map(_.get).toVector)
            case v  =>
              val glus = domains(v)
              var i    = 0
              while i < glus.length && found < cap do
                val glu = glus(i)
                if r1ok(v, glu) then
                  chosen(v) = Some(glu)
                  bt()
                  chosen(v) = None
                i += 1
              if i < glus.length then capped = true
    bt()
    (found, capped)

  // ---------- development and fingerprints ----------

  /** Develop the pattern (BFS over words, positions identified by rounding) out to `radius` plus a slack
    * annulus (paths may exit and re-enter). Returns None if any position is reached with stab-incompatible
    * stars — the pattern is then NOT globally consistent and is rejected: R1+R2 at the base star do not by
    * themselves guarantee developability (the loop-decomposition argument would need Stab-equivariance of the
    * pattern), so collision-freeness of the development is part of the acceptance criterion.
    */
  def developBall(
      g: StarGeom,
      pat: Pattern,
      stab: Vector[Mat],
      radius: Double
  ): Option[Vector[Iso]] =
    val isos     = g.u.indices.map(pat.iso).toVector
    val slack    = radius + 1.6
    val seen     = collection.mutable.Map.empty[(Long, Long, Long), Iso]
    var frontier = Vector(Iso(idMat, (0.0, 0.0, 0.0)))
    seen((0L, 0L, 0L)) = frontier.head
    var depth    = 0
    var clash    = false
    val maxDepth = math.max(14, (3.0 * slack).toInt) // word length must reach across the whole ball
    while frontier.nonEmpty && depth < maxDepth && !clash do
      frontier = frontier.flatMap { t =>
        isos.flatMap { gx =>
          val t2  = t.compose(gx)
          val pos = t2.t
          if vNorm(pos) <= slack + 1e-6 then
            val k = round4(pos)
            if seen.contains(k) then
              if seen(k).m.dist(t2.m) > 1e-4 && !stab.exists(s => (seen(k).m.t * t2.m).dist(s) < 1e-3)
              then clash = true
              None
            else
              seen(k) = t2
              Some(t2)
          else None
        }
      }
      depth += 1
    if clash then None else Some(seen.values.toVector)

  /** Canonical fingerprint of the ball of `radius` from a developed vertex list. */
  def fingerprintOf(
      corners: Vector[(Int, Vector[Vec])],
      stab: Vector[Mat],
      ball: Vector[Iso],
      radius: Double
  ): Vector[(Long, Long, Long)] =
    val entries                                    = ball.filter(t => vNorm(t.t) <= radius + 1e-6)
    def encode(s: Mat): Vector[(Long, Long, Long)] =
      entries
        .flatMap { t =>
          val p = round4(s(t.t))
          val m = s * t.m
          starSig(corners, m).flatMap((c, ds) => (c.toLong, 0L, 0L) +: ds) :+ p
        }
        .sorted
    stab.map(encode).min(using scala.math.Ordering.Implicits.seqOrdering)

  // ---------- the per-species driver ----------

  final case class Report(
      idx: Int,
      stabOrder: Int,
      cosetCounts: Vector[Int],
      forced: Boolean,       // single-coset everywhere: uniqueness holds by the forcing theorem
      skeletons: Int,        // consistent-domain skeletons searched (1 when forced)
      honeycombs: Int,       // distinct development fingerprints (radius 2.05)
      stableAtR3: Boolean,   // same count at radius 3.05
      patternsFound: Int,
      patternsRejected: Int, // passed R1+R2 but failed collision-free development
      capped: Boolean
  )

  private val patternCap  = 40
  private val skeletonCap = 5000

  /** Consistent skeletons: one coset (neighbor-star placement) per vertex, pruned by [[MonoShell]]'s pairwise
    * compatibility on representatives, enumerated by backtracking (never materialized as a product).
    */
  private def skeletonsOf(
      g: StarGeom,
      cosets: Vector[Vector[Vector[Glu]]],
      flags: Flags
  ): (Vector[Vector[Vector[Glu]]], Boolean) =
    val n                = cosets.size
    val out              = Vector.newBuilder[Vector[Vector[Glu]]]
    var count            = 0
    var capped           = false
    val chosen           = Array.fill(n)(-1)
    def bt(x: Int): Unit =
      if count >= skeletonCap then capped = true
      else if x == n then
        out += chosen.toVector.zipWithIndex.map((ci, v) => cosets(v)(ci))
        count += 1
      else
        cosets(x).indices.foreach { ci =>
          chosen(x) = ci
          val ok = (0 until x).forall(x2 =>
            MonoShell.compatible(g, x, cosets(x)(ci).head, x2, cosets(x2)(chosen(x2)).head, flags)
          )
          if ok then bt(x + 1)
          chosen(x) = -1
        }
    bt(0)
    (out.result(), capped)

  def analyze(idx: Int, flags: Flags): Report =
    val sp                  = species(idx)
    val g                   = geomOf(sp)
    val corners             = cornerData(g)
    val stab                = stabilizers(g, corners)
    val atlas               = g.u.indices.toVector.map(x => gluings(g, x, flags))
    // coset structure: group gluings by the placed neighbor star (g Stab)
    val cosets              = atlas.map { dom =>
      val reps = collection.mutable.ArrayBuffer.empty[(Glu, collection.mutable.ArrayBuffer[Glu])]
      for glu <- dom do
        reps.find((r, _) => inStab(matOf(r.rot).t * matOf(glu.rot), stab)) match
          case Some((_, members)) => members += glu
          case None               => reps += ((glu, collection.mutable.ArrayBuffer(glu)))
      reps.toVector.map(_._2.toVector)
    }
    val forced              = cosets.forall(_.size == 1)
    val fps                 = collection.mutable.Map.empty[Vector[(Long, Long, Long)], Vector[(Long, Long, Long)]]
    var nPat                = 0
    var nRejected           = 0
    var capped              = false
    val (skels, skelCapped) =
      if forced then (Vector(atlas), false)
      else skeletonsOf(g, cosets, flags)
    capped ||= skelCapped
    for domains <- skels do
      val cap    = if forced then 1 else patternCap
      val (n, c) = searchPatterns(
        g,
        domains,
        stab,
        cap,
        glus => {
          val pat = Pattern(g, glus)
          developBall(g, pat, stab, 3.05) match
            case None       => nRejected += 1 // development collision: pattern not globally consistent
            case Some(ball) =>
              val f2 = fingerprintOf(corners, stab, ball, 2.05)
              if !fps.contains(f2) then fps(f2) = fingerprintOf(corners, stab, ball, 3.05)
        }
      )
      nPat += n
      // forced species search with cap = 1 BY THEOREM (further patterns are Stab-rebased duplicates of
      // the single mono-species honeycomb), so that truncation misses no honeycomb and is not "capped"
      capped ||= (c && !forced)
    val stable              = fps.values.toVector.distinct.size == fps.size
    Report(idx, stab.size, cosets.map(_.size), forced, skels.size, fps.size, stable, nPat, nRejected, capped)

  /** The audit hook: all accepted patterns of a species, tagged by skeleton index, plus the geometry and
    * symmetry data the audit needs. Same search as `analyze` (same caps).
    */
  final case class Accepted(
      g: StarGeom,
      corners: Vector[(Int, Vector[Vec])],
      stab: Vector[Mat],
      skeletons: Vector[Vector[Vector[Glu]]],
      patterns: Vector[(Int, Pattern)]
  )

  def acceptedOf(idx: Int, flags: Flags): Accepted =
    val sp         = species(idx)
    val g          = geomOf(sp)
    val corners    = cornerData(g)
    val stab       = stabilizers(g, corners)
    val atlas      = g.u.indices.toVector.map(x => gluings(g, x, flags))
    val cosets     = atlas.map { dom =>
      val reps = collection.mutable.ArrayBuffer.empty[(Glu, collection.mutable.ArrayBuffer[Glu])]
      for glu <- dom do
        reps.find((r, _) => inStab(matOf(r.rot).t * matOf(glu.rot), stab)) match
          case Some((_, members)) => members += glu
          case None               => reps += ((glu, collection.mutable.ArrayBuffer(glu)))
      reps.toVector.map(_._2.toVector)
    }
    val forced     = cosets.forall(_.size == 1)
    val (skels, _) =
      if forced then (Vector(atlas), false)
      else skeletonsOf(g, cosets, flags)
    val pats       = Vector.newBuilder[(Int, Pattern)]
    for (domains, si) <- skels.zipWithIndex do
      val cap = if forced then 1 else patternCap
      searchPatterns(
        g,
        domains,
        stab,
        cap,
        glus => {
          val pat = Pattern(g, glus)
          if developBall(g, pat, stab, 3.05).isDefined then pats += ((si, pat))
        }
      )
    Accepted(g, corners, stab, skels, pats.result())

  /** The pattern table over the shell-surviving species. */
  lazy val results: (Vector[Report], Vector[String]) =
    val flags   = Flags()
    val (rs, _) = MonoShell.results
    val sat     = rs.filter(_._2.sat).map(_._1)
    (sat.map(i => analyze(i, flags)), flags.items.distinct.toVector)
